services:

  server:

    build:

      context: ../server

    container_name: kl-server

    restart: unless-stopped

    env_file:

      - ../server/.env

    ports:

      - "5000:5000"

    networks:

      - kl-network

  client:

    build:

      context: ../client

    container_name: kl-client

    restart: unless-stopped

    ports:

      - "3000:80"

    networks:

      - kl-network

networks:

  kl-network:

    external: true